
name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# FIXME: add no-openmp, and maybe -DCMAKE_BUILD_TYPE=Debug jobs

jobs:
  linux-ossfuzz:
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [ address, undefined, memory ]
        fuzzing_engine: [ libfuzzer, afl, honggfuzz ]
        include:
          - sanitizer: coverage
            fuzzing_engine: libfuzzer
          - sanitizer: introspector
            fuzzing_engine: libfuzzer
    uses: ./.github/workflows/CI-ossfuzz.yml
    with:
      sanitizer: ${{ matrix.sanitizer }}
      fuzzing_engine: ${{ matrix.fuzzing_engine }}
