
name: CI

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# FIXME: add no-openmp, and maybe -DCMAKE_BUILD_TYPE=Debug jobs

jobs:
  cache-rpuu:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            distro: "debian:bookworm-slim"
    uses: ./.github/workflows/CI-rpuu.yml
    with:
      distro: ${{ matrix.distro }}
  linux-fast:
    needs: cache-rpuu
    strategy:
      fail-fast: false
      matrix:
        os: [ linux ]
        compiler:
          - { distro: "debian:unstable-slim", family: LLVM, version: 18, CC: clang-18, CXX: clang++-18 }
        flavor: [ Release ]
    uses: ./.github/workflows/CI-linux.yml
    with:
      os: ${{ matrix.os }}
      distro: ${{ matrix.compiler.distro }}
      compiler-family: ${{ matrix.compiler.family }}
      compiler-version: ${{ matrix.compiler.version }}
      compiler-CC: ${{ matrix.compiler.CC }}
      compiler-CXX: ${{ matrix.compiler.CXX }}
      compiler-GCOV: ${{ matrix.compiler.GCOV }}
      compiler-CLANG_TIDY: ${{ matrix.compiler.CLANG_TIDY }}
      flavor: ${{ matrix.flavor }}
      enable-sample-based-testing: true
      rpuu-cache-key: ${{ needs.cache-rpuu.outputs.rpuu-cache-key }}
